language: php

php:
  - '7.4'

sudo: false

install:
  - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  - sudo apt install nodejs
  - npm install --global gulp-cli
  - npm install
  - composer update

script:
  - gulp test